### ISSUE TITLE
The pay with bitpay

### ISSUE THREAD

**Issue by teknology** [bitpay/woocommerce-plugin#46]
For some reason the pay with bitpay button is redirecting to a non recognized URL. which is. bitcoin:1vnfpsXm7ypVfUQp7SAUfrS4NABVGvyxf?amount=4.968399&r=https%3A%2F%2Fbitpay.com%2Fi%2FJLssvnZxN6x1s6WvbpiRn4

**Comment by sambohler** [comment]
The 'Pay with Bitcoin' button you're probably referencing is found on the BitPay invoice, and that URL attempts to open a Bitcoin wallet on the computer or device.  If you don't have a Bitcoin wallet program or app set to handle the bitcoin: protocol, it will be seen as a non recognized URL.  It would be like opening a mail: protocol URL without an email application installed.  Some web wallets allow you to register their website as a handler, and wallet apps for phones, of desktop wallets almost always do.
This is a user error and related to the BitPay invoice, not the BitPay for WooCommerce plugin, so I'm going to close this issue.  Please contact support@bitpay.com if you have any further questions.
