### ISSUE TITLE
Default entry for callback and redirect URLs?

### ISSUE THREAD

**Issue by shawaj** [bitpay/woocommerce-plugin#52]
Line 295 - `'placeholder' => WC()->api_request_url('WC_Gateway_Bitpay'),`

and 

Line 303 - `'placeholder' => $this->get_return_url(),`

Instead of having them as placeholders, would it not make more sense to have the notification and redirect URLs as the "default" setting? I would imagine that for pretty much every install of the plugin these standard URLs would be the default setting? 

And then people can just change them if they need to (which would likely not be very many people?)

Additionally, is there a way we can force a failed IPN callback to happen again for a previous payment from within our Bitpay account?

**Comment by sambohler** [comment]
> Instead of having them as placeholders, would it not make more sense to have the notification and redirect URLs as the "default" setting?

They are.  By leaving the fields blank, they are used by default.  The placeholders are simply there to indicate the value when you have left it blank.

**Comment by shawaj** [comment]
Leaving them empty, the IPN callback does not work though?

Any idea why?
