### ISSUE TITLE
API Not Working

### ISSUE THREAD

**Issue by shawaj** [bitpay/woocommerce-plugin#56]
We have it said to highest security / process time.

We have it set so that it goes to pending payment immediately, and then when the payment is completed it should go to the Processing status in WooCommerce.

However this never happens - it gets stuck in pending payment unless you manually update it.

Any idea why?

Thanks

**Comment by brianwang9100** [comment]
Hey Shawaj, 

Sorry we overlooked this issue. Does your problem still persist or should we still take a look into it? Looks like it's a problem with the IPN handling code.

If you still do have a problem, can you tell me the plugin version and woocommerce version?
