### ISSUE TITLE
API Fields are missing (no box to filled it with)

### ISSUE THREAD

**Issue by nyxzryu** [bitpay/woocommerce-plugin#58]
Hi, 

My API Files is missing, there's no box or form or whatever it is ( see attachment )

when i access mydomain.com/wp-content/plugins/bitpay-for-woocommerce/templates/pairing.tpl, it make me to download the pairing.tpl file. Actually my site force to use https at any http request via htacess.

I use the latest plugin and WP as i wrote now (8/8/2015)

images : 
![bitpay error](https://cloud.githubusercontent.com/assets/9864359/9149193/cbd247dc-3dc8-11e5-9f3b-e33d4bb8b306.png)

**Comment by nyxzryu** [comment]
It's strange that no log file created in the this plugin log

**Comment by brianwang9100** [comment]
Hey @nyxzryu, please check your permissions on the templates folder that contains pairing.tpl. The reason why the field isn't showing up is because your templates folder doesn't have the proper executable permissions. The permissions should be executable from the outside, so please chmod the templates folder to 755. 

```
chmod 755 templates
```

**Comment by nyxzryu** [comment]
Hi @brianwang9100, 

Already did that, the default permission were set at 755 and i just rechange the permission to be set at 755. However i still didn't see any changes

**Comment by brianwang9100** [comment]
@nyxzryu What are the permissions on the .tpl files themselves?

**Comment by nyxzryu** [comment]
@brianwang9100 Oh did not notices it, the files inside were set at 644 (for both pairing and token.tpl). So should i changes the both files ?

**Comment by brianwang9100** [comment]
@nyxzryu I highly doubt thats the problem (my files are running 644 by default, with templates/ set to 755). I'd try it and see if that works. If not, can you tell me what the ownership of the templates and the .tpl files are?

**Comment by nyxzryu** [comment]
Hi @brianwang9100 , I dont have the shell access. So any other option to fix this ?

**Comment by ionux** [comment]
@nyxzryu I'm looking at this now and will update as soon as I determine the issue.  If needed, I'll push out a new release today.  Thanks for your patience!

**Comment by brianwang9100** [comment]
Hey @nyxzryu, we're looking into this issue and you should be able to see the api field as long as the the folder is executable from outside groups. Do you think you can send us your apache2 server access and error logs?

**Comment by brianwang9100** [comment]
@nyxzryu, we may have found the source of the issue. in bitpay-for-woocommerce/class-wc-gateway-bitpay.php, there are two lines of code that may be causing the issue. On lines 337 and 338, change:

```
$pairing_form = file_get_contents(plugin_dir_url(__FILE__).'templates/pairing.tpl');
$token_format = file_get_contents(plugin_dir_url(__FILE__).'templates/token.tpl');

```
to:
```
$pairing_form = file_get_contents(dirname(__FILE__) . '/templates/pairing.tpl');
$token_format = file_get_contents(dirname(__FILE__) . '/templates/token.tpl');
```

Let us know if that works for you. If it does, we'll push a new release.
