### ISSUE TITLE
Logging messages while $wp_object_cache is destroyed

### ISSUE THREAD

**Issue by sjoerdmaessen** [bitpay/woocommerce-plugin#59]
I had an issue in the checkout where "/checkout/?wc-ajax=update_order_review" was called trough a XHR. The response was a JSON encoded success string as expected but also contained a PHP error after the payload complaining about the cache instance: "<b>Fatal error</b>:  Call to a member function get() on a non-object in <b>/wp-includes/cache.php</b> on line <b>113</b><br />".

As it turns out the instance of global $wp_object_cache; isn't available anymore in the __destruct of WC_Gateway_Bitpa when its trying to write a log message with the following code:
"$this->log('BitPay Woocommerce payment plugin object destroyed.')"

Environment:
PHP version: 5.5.30
Woocommerce version: 2.4.10
Plugin version: 2.2.7

ps no other plugins were active.

**Comment by kleetus** [comment]
this is fixed in 2.2.9
