### ISSUE TITLE
Many errors when running PHP 7 compatibility check

### ISSUE THREAD

**Issue by ajp8164** [bitpay/woocommerce-plugin#69]
I am using BitPay for Woocommerce v. 2.2.9 with PHP 7.1 and Wordpress 4.7.3.

I ran the php 7 compatibility check and the following errors occurred. Do you have plans for updating the plugin to be compatible with PHP7?

FILE: /home/cotosanc/public_html/zeta/wp-content/plugins/bitpay-for-woocommerce/lib/Bitpay/Client/ClientInterface.php

------------------------------------------------------------------------------------------------------------------------------------------------

FOUND 2 ERRORS AFFECTING 2 LINES

------------------------------------------------------------------------------------------------------------------------------------------------

19 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x6F'

20 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x00'

------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/cotosanc/public_html/zeta/wp-content/plugins/bitpay-for-woocommerce/lib/Bitpay/PublicKey.php

------------------------------------------------------------------------------------------------------------------------------------------------

FOUND 1 ERROR AFFECTING 1 LINE

------------------------------------------------------------------------------------------------------------------------------------------------

39 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x02'

------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/cotosanc/public_html/zeta/wp-content/plugins/bitpay-for-woocommerce/lib/Bitpay/PrivateKey.php

-------------------------------------------------------------------------------------------------------------------------------------------------

FOUND 2 ERRORS AFFECTING 2 LINES

-------------------------------------------------------------------------------------------------------------------------------------------------

210 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x80'

230 | ERROR | The behaviour of hexadecimal numeric strings was inconsistent prior to PHP 7 and support has been removed in PHP 7. Found: '0x80'

**Comment by pieterpoorthuis** [comment]
fixed in v2.2.12
