### ISSUE TITLE
Redirect page displays 'payment successful' even for unpaid invoices

### ISSUE THREAD

**Issue by pieterpoorthuis** [bitpay/woocommerce-plugin#81]
If a customer does not pay the BitPay invoice and waits for 15 minutes, the BitPay invoice will expire and displays a redirect link that takes the customer back to a 'payment successful' page.

Please change the 'payment successful' page to display:
1) 'payment received' only if the order has been paid
2) 'waiting for payment' if the order is still unpaid

**Comment by gillesgoetsch** [comment]
+1

**Comment by pieterpoorthuis** [comment]
solved in release 2.2.13
