### ISSUE TITLE
get_billing_email() Method creates fatal Error

### ISSUE THREAD

**Issue by gillesgoetsch** [bitpay/woocommerce-plugin#83]
.. and therefore a Internal Server Error 500 when Debug mode is set to false.

This output is generated in the ajax-call:
`Fatal error: Uncaught Error: Call to undefined method WC_Order::get_billing_email() in PATH/plugins/bitpay-for-woocommerce/class-wc-gateway-bitpay.php on line 677`

.. uncommenting this Line seems to bypass the Error and starts the redirecting process ..

**WP:** 4.8.2
**WC:** 2.6.14
**Bitpay:** 2.2.12
**PHP:** 7.1.8 & 5.6

**Comment by pieterpoorthuis** [comment]
Thanks for reporting. We've reproduced on other environments as well (e.g. PHP 5.4.45, WP 4.7.8 & WC 2.5.5). We are working on a fix.

**Comment by pieterpoorthuis** [comment]
Same issue is happening in WP 4.9.1 / WC 2.5.2:
6 PHP Fatal error: Call to undefined method WC_Order::get_billing_email() in /wp-content/plugins/bitpay-for-woocommerce/class-wc-gateway-bitpay.php on line 677

2 PHP Fatal error: Call to undefined function wc_help_tip() in /wp-content/plugins/woocommerce-customer-order-csv-import/lib/skyverge/woocommerce/class-sv-wc-plugin-compatibility.php on line 104

**Comment by pieterpoorthuis** [comment]
Fixed in release 2.2.14
