### ISSUE TITLE
wrong function call resulting in undefined wc_reduce_stock_levels()

### ISSUE THREAD

**Issue by gillesgoetsch** [bitpay/woocommerce-plugin#84]
There are two ways in the source of reducing the stock levels, of which one is commented out:

```
// Reduce stock levels
//$order->reduce_order_stock(); 
wc_reduce_stock_levels($order_id);
```

The wc_reduce_stock_levels() function is undefined and breaks the payment process, output from the ajax-call:

```
> Fatal error: Uncaught Error: Call to undefined function wc_reduce_stock_levels() in PATH/plugins/bitpay-for-woocommerce/class-wc-gateway-bitpay.php:709
> Stack trace:
> #0 PATH/plugins/woocommerce/includes/class-wc-checkout.php(663): WC_Gateway_Bitpay->process_payment(17145)
> #1 PATH/plugins/woocommerce/includes/class-wc-ajax.php(472): WC_Checkout->process_checkout()
> #2 PATH/wp/wp-includes/class-wp-hook.php(298): WC_AJAX::checkout('')
> #3 PATH/wp/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
> #4 PATH/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
> #5 PATH/plugins/woocommerce/includes/class-wc-ajax.php(82): do_action('wc_ajax_checkou...')
> #6 /PATH/httpdocs_ in PATH/plugins/bitpay-for-woocommerce/class-wc-gateway-bitpay.php on line 709
```

There is a thread which suggests to instead use the other function (the one that is commented out in the source):

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/228#issuecomment-267983940

Therefore flipping it to:

```
// Reduce stock levels
$order->reduce_order_stock(); 
//wc_reduce_stock_levels($order_id);
```

.. makes the plugin work again. I think this needs a cleanup and proper handling which function has to be executed ..

**WP:** 4.8.2
**WC:** 2.6.14
**Bitpay:** 2.2.12
**PHP:** 7.1.8 & 5.6

**Comment by pieterpoorthuis** [comment]
solved in release 2.2.13
