### ISSUE TITLE
compatibility with Wordpress 5

### ISSUE THREAD

**Issue by Narek13** [bitpay/woocommerce-plugin#94]
Hi,
I wonder if this plugin is working with new wordpress versions or it is not supported anymore ?

**Comment by thejoshualewis** [comment]
Hi @Narek13 ,

We actually just released a newer version this week that simplifies the integration. This current one will be discontinued June 9th 2019 as we migrate users over.

Here is a link to the new version
https://wordpress.org/plugins/bitpay-checkout-for-woocommerce/
